name: ocaes-py3
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.3
    - pyomo=5.7
    - pandas=1.0.5
    - numpy=1.18.5
    - seaborn=0.10.1
    - matplotlib=3.2.2
    - scipy=1.5.0
    - joblib=0.16.0
    - xlrd=1.2.0
    - glpk=